version: '3'
run: 'always' # "always" | "once" | "when_changed"
method: 'checksum' # "checksum" | "timestamp" | "none"
interval: '5s'
# set:
#   - -e # Exit immediately if command returns a non-zero status
#   - -x # Print commands
# shopt:
#   - -s
#   - dotglob
silent: false
output: 'interleaved' # "interleaved" | "group" | "prefixed"

dotenv:
  - .env
  - .local.env

includes:
  adb: {taskfile: './taskfile.d/adb.yaml', optional: true}
  ansible: {taskfile: './taskfile.d/ansible.yaml', optional: true}
  apt: {taskfile: './taskfile.d/apt.yaml', optional: true}
  astro: {taskfile: './taskfile.d/astro.yaml', optional: true}
  bin: {taskfile: './taskfile.d/bin.yaml', optional: true}
  brew: {taskfile: './taskfile.d/brew.yaml', optional: true}
  cargo: {taskfile: './taskfile.d/cargo.yaml', optional: true}
  cheatsheet: {taskfile: './taskfile.d/cheatsheet.yaml', optional: true}
  choco: {taskfile: './taskfile.d/choco.yaml', optional: true}
  coolify: {taskfile: './taskfile.d/coolify.yaml', optional: true}
  dotnet: {taskfile: './taskfile.d/dotnet.yaml', optional: true}
  git: {taskfile: './taskfile.d/git.yaml', optional: true}
  go: {taskfile: './taskfile.d/go.yaml', optional: true}
  k8s: {taskfile: './taskfile.d/k8s.yaml', optional: true}
  conda: {taskfile: './taskfile.d/conda.yaml', optional: true}
  nix: {taskfile: './taskfile.d/nix.yaml', optional: true}
  npm: {taskfile: './taskfile.d/npm.yaml', optional: true}
  pipx: {taskfile: './taskfile.d/pipx.yaml', optional: true}
  powershell: {taskfile: './taskfile.d/powershell.yaml', optional: true, aliases: [pwsh, ps]}
  rclone: {taskfile: './taskfile.d/rclone.yaml', optional: true}
  reg: {taskfile: './taskfile.d/reg.yaml', optional: true}
  restic: {taskfile: './taskfile.d/restic.yaml', optional: true}
  rye: {taskfile: './taskfile.d/rye.yaml', optional: true}
  scoop: {taskfile: './taskfile.d/scoop.yaml', optional: true}
  sops: {taskfile: './taskfile.d/sops.yaml', optional: true}
  ssh: {taskfile: './taskfile.d/ssh.yaml', optional: true}
  stack: {taskfile: './taskfile.d/stack.yaml', optional: true}
  systemd: {taskfile: './taskfile.d/systemd.yaml', optional: true}
  task: {taskfile: './taskfile.d/task.yaml', optional: true}
  vfox: {taskfile: './taskfile.d/vfox.yaml', optional: true}
  volta: {taskfile: './taskfile.d/volta.yaml', optional: true}
  winget: {taskfile: './taskfile.d/winget.yaml', optional: true}
  w2: {taskfile: './taskfile.d/w2.yaml', optional: true}
  wsl: {taskfile: './taskfile.d/wsl.yaml', optional: true}
  x: {taskfile: './taskfile.d/x-cmd.yaml', optional: true}
  yum: {taskfile: './taskfile.d/yum.yaml', optional: true}

  ls: {taskfile: './taskfile.d/task-ls.yaml', optional: false, aliases: [list, l]}
  ll: {taskfile: './taskfile.d/task-ll.yaml', optional: false, aliases: [list-all, la]}

tasks:

  default:
    cmds:
      - task: ll
