# "$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

--when.repositories = [
  'D:/home/libraries/Documents/repos/git',
  'D:/home/apps/scoop/buckets',
  'D:/home',
]

[user]
name = "gdm257"
email = "gdm@disroot.org"

[git]
sign-on-push = true
# Configure signing backend as before, but lazily signing only on push
[signing]
behavior = "keep" # drop, keep, own, force
backend = "ssh"
# key = "~/.ssh/keys.d/gdm257_sign_ed25519.pub"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICXLvOF9mX9N80IjkHimhAQRr+0WIdzwW1IkOQoFB0NK"
backends.ssh.allowed-signers = "~/.ssh/allowed_signers"
