"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[git]
private-commits = '''description(glob:'private:*') | description(glob:'local:*')'''

[ui]
show-cryptographic-signatures = true
editor = "vim"
# diff-editor = "vimdiff" # out of the box: kdiff3 meld mergiraf smerge vimdiff vscode vscodium
# diff-formatter = ":git" # required by `delta`
# pager = ["delta", "--pager", "less -FRX"] # Keeps output from the terminal after closing the pager

# [merge-tools.meld]
# program = "meld"
# merge-args = ["$left", "$base", "$right", "-o", "$output", "--auto-merge"]
# edit-args = ["--newtab","$left","$right",]

# [merge-tools.kdiff3]
# program  = "kdiff3"     # Defaults to the name of the tool if not specified
# merge-args = ["$base", "$left", "$right", "-o", "$output", "--auto"]

# [merge-tools.vimdiff]
# program = "vim"
# merge-args = ["-f", "-d", "$output", "-M",
#     "$left", "$base", "$right",
#     "-c", "wincmd J", "-c", "set modifiable",
#     "-c", "set write"]
# merge-tool-edits-conflict-markers = true    # See below for an explanation
